import Body from '@/components/Body/Body';
import VideoMain from '@/components/Video/VideoMain';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Packaging School | CMPM</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='w-full h-full bg-dark flex flex-col align-middle'>
        <VideoMain />
        <Body />
      </main>
    </>
  );
}
